### PR TITLE
Fix mod path

### PR DESCRIPTION
**Pull request by ffaristocrat**
Combine the path to the mod directory in an os agnostic way.

### CODE REVIEW

**Comment by ffaristocrat** [comment]
Fixes #8

**Comment by schreiaj** [comment]
Reasons not to use https://msdn.microsoft.com/en-us/library/dd991142(v=vs.110).aspx instead of the nested `Path.Combine` calls?

**Comment by ffaristocrat** [comment]
That's what I initially tried but it looks like the list version isn't in .NET 3.5 which is what BT uses.

**Comment by schreiaj** [comment]
Ugh... it's 2018 and C# doesn't support variadic arguments...

**Comment by Mpstark** [comment]
I'll prob merge tomorrow, I see no issues with this right now, but I obviously will want to try it out, make sure it doesn't break in my setup.

**Comment by CptMoore** [comment]
@schreiaj 
BattleTechs Unity Engine is using .NET 3.5 is from 2007 . Unity in 2018 has officially updated to .NET 4.7 which is up to date (2017). .NET determines what system classes and methods you can use.  C# is the language and supported variadic arguments from the beginning (2002).

**Pull request merged**
